apiVersion: "kubeflow.org/v1"
kind: "PyTorchJob"
metadata:
  name: "sd-train-he1k"
  namespace: "kubeflow-app"
spec:
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: Never
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          #hostNetwork: true
          volumes:
          - hostPath:
              path: /pfs/sshare/app
              type: Directory
            name: pfs-volume
          # - emptyDir:
          #     medium: Memory
          #     sizeLimit: 80Gi
          #   name: sugaku-volume
          schedulerName: volcano
          containers:
            - name: pytorch
              image: ccr-276x7ilk-vpc.cnc.bj.baidubce.com/ai/sd-postrain:cuda11.7-wandb
              imagePullPolicy: Always
              command: ["bash","-c"]
              args:
                - |
                  accelerate launch --config_file /pfs/sshare/app/xujianbo/diffusers/maleo/default_config.yaml \
                  --machine_rank=${RANK} \
                  --main_process_ip=${MASTER_ADDR} \
                  --main_process_port=${MASTER_PORT} \
                  --num_machines=${WORLD_SIZE} \
                  --num_processes=8 \
                  --gpu_ids=all \
                  "/pfs/sshare/app/xujianbo/diffusers/examples/text_to_image/train_text_to_image_sdxl.py" \
                  --pretrained_model_name_or_path="/pfs/sshare/app/zhangsan/models/stable-diffusion-xl-base-1.0" \
                  --train_data_dir="/pfs/sshare/app/dataset/laion-high-aesthetics_unpacked_000" \
                  --train_data_type="imagefolder" \
                  --caption_column=caption --report_to=wandb \
                  --use_ema --resolution=1024 --train_batch_size=2 \
                  --gradient_accumulation_steps=1 --gradient_checkpointing --max_train_steps=1500 \
                  --learning_rate=1e-05 --max_grad_norm=1 --lr_scheduler=constant \
                  --lr_warmup_steps=0 --output_dir="/pfs/sshare/app/xujianbo/diffusers/output/sdxl-he1k-ema"
              env:
                - name: NCCL_IB_DISABLE
                  value: "0"
                - name: NCCL_DEBUG
                  value: "INFO"
                - name: NCCL_IB_GID_INDEX
                  value: "3"
                - name: WANDB_API_KEY
                  # xujianbo-wandb
                  value: "2004630b97157ba54346d1f5e39fddd7b08d0b31"
              securityContext:
                privileged: true
                capabilities:
                  add: [ "IPC_LOCK" ]
              resources: 
                limits:
                  cpu: 48
                  memory: 360Gi
                  nvidia.com/gpu: 8
                  rdma/hca : 1
              volumeMounts:
              - mountPath: /pfs/sshare/app
                name: pfs-volume
              # - mountPath: /dev/shm
              #   name: sugaku-volume
